[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.0",
    "openai-agents[voice]>=0.3.3",
    "uvicorn>=0.37.0",
    "websockets>=15.0.1",
]
